language: ruby

rvm:
  - 2.3.6
  - 2.4.3
  - 2.5.0

gemfile:
  - gemfiles/Gemfile.rails-4.1.x
  - gemfiles/Gemfile.rails-4.2.x
  - gemfiles/Gemfile.rails-5.0.x
  - gemfiles/Gemfile.rails-5.1.x
  - Gemfile

script:
  - bundle exec rake test

matrix:
  exclude:
    - rvm: 2.3.6
      gemfile: gemfiles/Gemfile.rails-5.0.x
    - rvm: 2.3.6
      gemfile: gemfiles/Gemfile.rails-5.1.x
